# start by pulling the python image
FROM myapp:latest

# copy the requirements file into the image
COPY ./src/requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip3 install -r requirements.txt

# copy every content from the local file to the image
ADD ./src /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python3" ]

CMD ["view.py" ]
