apiVersion: v1
kind: Service 
metadata:
  name: {{ .Values.myappService.name }}
  namespace: {{ .Values.metaInfo.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: {{ .Values.myappDeploy.name  }}
  ports: 
    - name: {{ .Values.myappService.PortName }}
      port: {{ .Values.myappService.Port }} # Service Port
      targetPort: {{ .Values.myappService.TargetPort }} # Container Port
